name: Build and Publish
on:
  push:
    tags:
      - 'msf-release-[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Pull Github code
        uses: actions/checkout@v4
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Package
        run: yarn ci
      - name: Build docker image
        run: docker build -t implementer-interface:latest -f package/docker/Dockerfile .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'implementer-interface:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.BAHMNI_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.BAHMNI_LITE_AWS_SECRET_KEY }}
          aws-region: ${{ secrets.BAHMNI_LITE_AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set Image tag varaible
        run: echo "ARTIFACT_VERSION=$(cat package/.appversion)-$GITHUB_REF_NAME" >> $GITHUB_ENV
      - name: Tag and Push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: bahmni-msf-lite/implementer-interface
          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
        run: |
          echo $APP_VERSION
          docker tag implementer-interface:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
